import {
  SiPython,
  SiTypescript,
  SiJavascript,
  SiC,
  SiCplusplus,
  SiRust,
  SiDart,
  SiReact,
  SiNextdotjs,
  SiFlutter,
  SiTauri,
  SiHtml5,
  SiFastapi,
  SiPostgresql,
  SiSqlite,
  SiRedis,
  SiFirebase,
  SiSupabase,
  SiPytorch,
  SiOllama,
  SiN8N,
  SiEspressif,
  SiSharp,
} from "react-icons/si";
import type { IconType } from "react-icons";

export const techIcons: Record<string, IconType> = {
  "Python": SiPython,
  "TypeScript/JavaScript": SiTypescript,
  "JavaScript": SiJavascript,
  "C/C++": SiCplusplus,
  "C": SiC,
  "C#": SiSharp,
  "Rust": SiRust,
  "Dart": SiDart,
  "React": SiReact,
  "Next.js": SiNextdotjs,
  "Flutter": SiFlutter,
  "Tauri": SiTauri,
  "HTML/CSS": SiHtml5,
  "FastAPI": SiFastapi,
  "PostgreSQL": SiPostgresql,
  "SQLite": SiSqlite,
  "Redis": SiRedis,
  "Firebase": SiFirebase,
  "Supabase": SiSupabase,
  "PyTorch transfer learning": SiPytorch,
  "Ollama & LLM APIs": SiOllama,
  "n8n automation": SiN8N,
  "ESP32": SiEspressif,
};
